<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Universe.Carotene.Union.SourceGenerator</PackageId>
    <VersionPrefix>0.0.1-alpha.1.0</VersionPrefix>
  </PropertyGroup>
</Project>
